[package]
name = "telio-utils"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/NordSecurity/libtelio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.21"
thiserror = "1.0.30"
tokio = { version = ">=1.22", features = ["time"] }

[dev-dependencies]
tokio = { version = ">=1.22", features = ["time","macros","rt"] }
log = {version = "0.4.14", features = ["max_level_debug"]}
